version: 1
accounts:
  - name: user1
    coins: ["1000token", "100000000stake", "999999999999stos"]
  - name: user2
    coins: ["500token"]
validator:
  name: user1
  staked: "100000000stake"
faucet:
  name: user1
  coins: ["999999999999stos"]
  coins_max: ["2000stos"]
  host: 0.0.0.0
  port: 54321
