version: 1
accounts:
  - name: user1
    coins: ["8888888888888stos"]
  - name: user2
    coins: ["500stos"]
validator:
  name: user1
  staked: "10000000stos"
faucet:
  name: user1
  coins: ["999999999999stos"]
  coins_max: ["2000stos"]
  host: 0.0.0.0
  port: 54321