syntax = "proto3";
package stratos.sds.v1;

option go_package = "github.com/stratosnet/stratos-chain/x/sds/types";

// EventPrePay is emitted on Msg/MsgPrepay
message EventPrePay {
  string sender = 1;
  string beneficiary = 2;
  string amount = 3;
  string purchased_noz = 4;
}

// EventFileUpload is emitted on Msg/MsgFileUpload
message EventFileUpload {
  string sender = 1;
  string reporter = 2;
  string uploader = 3;
  string file_hash = 4;
}

// EventNewFilesUploaded is emitted in EndBlocker on Msg/MsgFileUpload
message EventNewFilesUploaded {
  int64 height = 1;
  repeated NewFileMerkleProof proofs = 2;
}

message NewFileMerkleProof {
  string file_hash = 1;
  int64 total = 2;
  int64 index = 3;
  bytes leaf_hash = 4;
  repeated bytes aunts = 5;
}
