syntax = "proto3";
package stratos.sds.v1;

import "gogoproto/gogo.proto";
import "amino/amino.proto";
import "stratos/sds/v1/sds.proto";

option (gogoproto.equal_all) = true;
option go_package = "github.com/stratosnet/stratos-chain/x/sds/types";

// GenesisState defines the register module's genesis state.
message GenesisState {
  Params                    params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true,
    (gogoproto.jsontag) = "params",
    (gogoproto.moretags) = "yaml:\"params\""
  ];
  bytes merkle_root = 2 [
    (amino.dont_omitempty) = true,
    (gogoproto.jsontag) = "merkle_root",
    (gogoproto.moretags) = "yaml:\"merkle_root\""
  ];
  repeated MerkleRoot previous_merkle_roots = 3 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true,
    (gogoproto.jsontag) = "previous_merkle_roots",
    (gogoproto.moretags) = "yaml:\"previous_merkle_roots\""
  ];
}

message MerkleRoot {
  int64 height = 1 [
    (gogoproto.jsontag) = "height",
    (gogoproto.moretags) = "yaml:\"height\""
  ];
  bytes root = 2 [
    (gogoproto.jsontag) = "root",
    (gogoproto.moretags) = "yaml:\"root\""
  ];
}
