// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stratos/register/v1/register.proto

package v0_10_0

import (
	fmt "fmt"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	types2 "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the Register module parameters
type Params struct {
	BondDenom               string        `protobuf:"bytes,1,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom" yaml:"bond_denom"`
	UnbondingThreasholdTime time.Duration `protobuf:"bytes,2,opt,name=unbonding_threashold_time,json=unbondingThreasholdTime,proto3,stdduration" json:"unbonding_threashold_time" yaml:"unbonding_threashold_time"`
	UnbondingCompletionTime time.Duration `protobuf:"bytes,3,opt,name=unbonding_completion_time,json=unbondingCompletionTime,proto3,stdduration" json:"unbonding_completion_time" yaml:"unbonding_completion_time"`
	MaxEntries              uint32        `protobuf:"varint,4,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries" yaml:"max_entries",omitempty`
	ResourceNodeRegEnabled  bool          `protobuf:"varint,5,opt,name=resource_node_reg_enabled,json=resourceNodeRegEnabled,proto3" json:"resource_node_reg_enabled" yaml:"resource_node_reg_enabled"`
	ResourceNodeMinDeposit  types.Coin    `protobuf:"bytes,6,opt,name=resource_node_min_deposit,json=resourceNodeMinDeposit,proto3" json:"resource_node_min_deposit" yaml:"resource_node_min_deposit"`
	VotingPeriod            time.Duration `protobuf:"bytes,7,opt,name=voting_period,json=votingPeriod,proto3,stdduration" json:"voting_period" yaml:"voting_period"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBondDenom() string {
	if m != nil {
		return m.BondDenom
	}
	return ""
}

func (m *Params) GetUnbondingThreasholdTime() time.Duration {
	if m != nil {
		return m.UnbondingThreasholdTime
	}
	return 0
}

func (m *Params) GetUnbondingCompletionTime() time.Duration {
	if m != nil {
		return m.UnbondingCompletionTime
	}
	return 0
}

func (m *Params) GetMaxEntries() uint32 {
	if m != nil {
		return m.MaxEntries
	}
	return 0
}

func (m *Params) GetResourceNodeRegEnabled() bool {
	if m != nil {
		return m.ResourceNodeRegEnabled
	}
	return false
}

func (m *Params) GetResourceNodeMinDeposit() types.Coin {
	if m != nil {
		return m.ResourceNodeMinDeposit
	}
	return types.Coin{}
}

func (m *Params) GetVotingPeriod() time.Duration {
	if m != nil {
		return m.VotingPeriod
	}
	return 0
}

type ResourceNode struct {
	NetworkAddress  string                                 `protobuf:"bytes,1,opt,name=network_address,json=networkAddress,proto3" json:"network_address" yaml:"network_address"`
	Pubkey          *types1.Any                            `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey" yaml:"pubkey"`
	Suspend         bool                                   `protobuf:"varint,3,opt,name=suspend,proto3" json:"suspend" yaml:"suspend"`
	Status          types2.BondStatus                      `protobuf:"varint,4,opt,name=status,proto3,enum=cosmos.staking.v1beta1.BondStatus" json:"status" yaml:"status"`
	Tokens          github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=tokens,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"tokens" yaml:"tokens"`
	OwnerAddress    string                                 `protobuf:"bytes,6,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address" yaml:"owner_address"`
	Description     Description                            `protobuf:"bytes,7,opt,name=description,proto3" json:"description" yaml:"description"`
	CreationTime    time.Time                              `protobuf:"bytes,8,opt,name=creation_time,json=creationTime,proto3,stdtime" json:"creation_time" yaml:"creation_time"`
	NodeType        uint32                                 `protobuf:"varint,9,opt,name=node_type,json=nodeType,proto3" json:"node_type" yaml:"node_type"`
	EffectiveTokens github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,10,opt,name=effective_tokens,json=effectiveTokens,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"effective_tokens" yaml:"effective_tokens"`
}

func (m *ResourceNode) Reset()         { *m = ResourceNode{} }
func (m *ResourceNode) String() string { return proto.CompactTextString(m) }
func (*ResourceNode) ProtoMessage()    {}
func (*ResourceNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{1}
}
func (m *ResourceNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResourceNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResourceNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResourceNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceNode.Merge(m, src)
}
func (m *ResourceNode) XXX_Size() int {
	return m.Size()
}
func (m *ResourceNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceNode.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceNode proto.InternalMessageInfo

func (m *ResourceNode) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

func (m *ResourceNode) GetPubkey() *types1.Any {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *ResourceNode) GetSuspend() bool {
	if m != nil {
		return m.Suspend
	}
	return false
}

func (m *ResourceNode) GetStatus() types2.BondStatus {
	if m != nil {
		return m.Status
	}
	return types2.Unspecified
}

func (m *ResourceNode) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *ResourceNode) GetDescription() Description {
	if m != nil {
		return m.Description
	}
	return Description{}
}

func (m *ResourceNode) GetCreationTime() time.Time {
	if m != nil {
		return m.CreationTime
	}
	return time.Time{}
}

func (m *ResourceNode) GetNodeType() uint32 {
	if m != nil {
		return m.NodeType
	}
	return 0
}

type MetaNode struct {
	NetworkAddress string                                 `protobuf:"bytes,1,opt,name=network_address,json=networkAddress,proto3" json:"network_address" yaml:"network_address"`
	Pubkey         *types1.Any                            `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey" yaml:"pubkey"`
	Suspend        bool                                   `protobuf:"varint,3,opt,name=suspend,proto3" json:"suspend" yaml:"suspend"`
	Status         types2.BondStatus                      `protobuf:"varint,4,opt,name=status,proto3,enum=cosmos.staking.v1beta1.BondStatus" json:"status" yaml:"status"`
	Tokens         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=tokens,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"tokens" yaml:"tokens"`
	OwnerAddress   string                                 `protobuf:"bytes,6,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address" yaml:"owner_address"`
	Description    Description                            `protobuf:"bytes,7,opt,name=description,proto3" json:"description" yaml:"description"`
	CreationTime   time.Time                              `protobuf:"bytes,8,opt,name=creation_time,json=creationTime,proto3,stdtime" json:"creation_time" yaml:"creation_time"`
}

func (m *MetaNode) Reset()         { *m = MetaNode{} }
func (m *MetaNode) String() string { return proto.CompactTextString(m) }
func (*MetaNode) ProtoMessage()    {}
func (*MetaNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{2}
}
func (m *MetaNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetaNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetaNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetaNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaNode.Merge(m, src)
}
func (m *MetaNode) XXX_Size() int {
	return m.Size()
}
func (m *MetaNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaNode.DiscardUnknown(m)
}

var xxx_messageInfo_MetaNode proto.InternalMessageInfo

func (m *MetaNode) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

func (m *MetaNode) GetPubkey() *types1.Any {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *MetaNode) GetSuspend() bool {
	if m != nil {
		return m.Suspend
	}
	return false
}

func (m *MetaNode) GetStatus() types2.BondStatus {
	if m != nil {
		return m.Status
	}
	return types2.Unspecified
}

func (m *MetaNode) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *MetaNode) GetDescription() Description {
	if m != nil {
		return m.Description
	}
	return Description{}
}

func (m *MetaNode) GetCreationTime() time.Time {
	if m != nil {
		return m.CreationTime
	}
	return time.Time{}
}

type MetaNodeRegistrationVotePool struct {
	NetworkAddress string    `protobuf:"bytes,1,opt,name=network_address,json=networkAddress,proto3" json:"network_address" yaml:"network_address"`
	ApproveList    []string  `protobuf:"bytes,2,rep,name=approve_list,json=approveList,proto3" json:"approve_list" yaml:"approve_list"`
	RejectList     []string  `protobuf:"bytes,3,rep,name=reject_list,json=rejectList,proto3" json:"reject_list" yaml:"reject_list"`
	ExpireTime     time.Time `protobuf:"bytes,4,opt,name=expire_time,json=expireTime,proto3,stdtime" json:"expire_time" yaml:"expire_time"`
	IsVotePassed   bool      `protobuf:"varint,5,opt,name=is_vote_passed,json=isVotePassed,proto3" json:"is_vote_passed" yaml:"is_vote_passed"`
}

func (m *MetaNodeRegistrationVotePool) Reset()         { *m = MetaNodeRegistrationVotePool{} }
func (m *MetaNodeRegistrationVotePool) String() string { return proto.CompactTextString(m) }
func (*MetaNodeRegistrationVotePool) ProtoMessage()    {}
func (*MetaNodeRegistrationVotePool) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{3}
}
func (m *MetaNodeRegistrationVotePool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetaNodeRegistrationVotePool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetaNodeRegistrationVotePool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetaNodeRegistrationVotePool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaNodeRegistrationVotePool.Merge(m, src)
}
func (m *MetaNodeRegistrationVotePool) XXX_Size() int {
	return m.Size()
}
func (m *MetaNodeRegistrationVotePool) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaNodeRegistrationVotePool.DiscardUnknown(m)
}

var xxx_messageInfo_MetaNodeRegistrationVotePool proto.InternalMessageInfo

func (m *MetaNodeRegistrationVotePool) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

func (m *MetaNodeRegistrationVotePool) GetApproveList() []string {
	if m != nil {
		return m.ApproveList
	}
	return nil
}

func (m *MetaNodeRegistrationVotePool) GetRejectList() []string {
	if m != nil {
		return m.RejectList
	}
	return nil
}

func (m *MetaNodeRegistrationVotePool) GetExpireTime() time.Time {
	if m != nil {
		return m.ExpireTime
	}
	return time.Time{}
}

func (m *MetaNodeRegistrationVotePool) GetIsVotePassed() bool {
	if m != nil {
		return m.IsVotePassed
	}
	return false
}

type Description struct {
	Moniker         string `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker" yaml:"moniker"`
	Identity        string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity" yaml:"identity",omitempty`
	Website         string `protobuf:"bytes,3,opt,name=website,proto3" json:"website" yaml:"website",omitempty`
	SecurityContact string `protobuf:"bytes,4,opt,name=security_contact,json=securityContact,proto3" json:"security_contact" yaml:"security_contact",omitempty`
	Details         string `protobuf:"bytes,5,opt,name=details,proto3" json:"details" yaml:"details",omitempty`
}

func (m *Description) Reset()         { *m = Description{} }
func (m *Description) String() string { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()    {}
func (*Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{4}
}
func (m *Description) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Description.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Description.Merge(m, src)
}
func (m *Description) XXX_Size() int {
	return m.Size()
}
func (m *Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Description proto.InternalMessageInfo

func (m *Description) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *Description) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Description) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Description) GetSecurityContact() string {
	if m != nil {
		return m.SecurityContact
	}
	return ""
}

func (m *Description) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

// UnbondingNode stores all of a single delegator's unbonding bonds
// for a single unbonding node in a time-ordered list
type UnbondingNode struct {
	NetworkAddr string                `protobuf:"bytes,1,opt,name=network_addr,json=networkAddr,proto3" json:"network_addr" yaml:"network_addr"`
	IsMetaNode  bool                  `protobuf:"varint,2,opt,name=is_meta_node,json=isMetaNode,proto3" json:"is_meta_node" yaml:"is_meta_node"`
	Entries     []*UnbondingNodeEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries" yaml:"entries"`
}

func (m *UnbondingNode) Reset()         { *m = UnbondingNode{} }
func (m *UnbondingNode) String() string { return proto.CompactTextString(m) }
func (*UnbondingNode) ProtoMessage()    {}
func (*UnbondingNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{5}
}
func (m *UnbondingNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingNode.Merge(m, src)
}
func (m *UnbondingNode) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingNode) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingNode.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingNode proto.InternalMessageInfo

func (m *UnbondingNode) GetNetworkAddr() string {
	if m != nil {
		return m.NetworkAddr
	}
	return ""
}

func (m *UnbondingNode) GetIsMetaNode() bool {
	if m != nil {
		return m.IsMetaNode
	}
	return false
}

func (m *UnbondingNode) GetEntries() []*UnbondingNodeEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type UnbondingNodeEntry struct {
	CreationHeight int64                                   `protobuf:"varint,1,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height" yaml:"creation_height"`
	CompletionTime time.Time                               `protobuf:"bytes,2,opt,name=completion_time,json=completionTime,proto3,stdtime" json:"creation_time" yaml:"creation_time"`
	InitialBalance *github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=initial_balance,json=initialBalance,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"initial_balance" yaml:"initial_balance"`
	Balance        *github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=balance,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"balance" yaml:"balance"`
}

func (m *UnbondingNodeEntry) Reset()         { *m = UnbondingNodeEntry{} }
func (m *UnbondingNodeEntry) String() string { return proto.CompactTextString(m) }
func (*UnbondingNodeEntry) ProtoMessage()    {}
func (*UnbondingNodeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef1e3aeec8499d6, []int{6}
}
func (m *UnbondingNodeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingNodeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingNodeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingNodeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingNodeEntry.Merge(m, src)
}
func (m *UnbondingNodeEntry) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingNodeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingNodeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingNodeEntry proto.InternalMessageInfo

func (m *UnbondingNodeEntry) GetCreationHeight() int64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *UnbondingNodeEntry) GetCompletionTime() time.Time {
	if m != nil {
		return m.CompletionTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Params)(nil), "stratos.register.v1.Params")
	proto.RegisterType((*ResourceNode)(nil), "stratos.register.v1.ResourceNode")
	proto.RegisterType((*MetaNode)(nil), "stratos.register.v1.MetaNode")
	proto.RegisterType((*MetaNodeRegistrationVotePool)(nil), "stratos.register.v1.MetaNodeRegistrationVotePool")
	proto.RegisterType((*Description)(nil), "stratos.register.v1.Description")
	proto.RegisterType((*UnbondingNode)(nil), "stratos.register.v1.UnbondingNode")
	proto.RegisterType((*UnbondingNodeEntry)(nil), "stratos.register.v1.UnbondingNodeEntry")
}

func init() {
	proto.RegisterFile("stratos/register/v1/register.proto", fileDescriptor_fef1e3aeec8499d6)
}

var fileDescriptor_fef1e3aeec8499d6 = []byte{
	// 1465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcf, 0x6f, 0xd4, 0x46,
	0x1b, 0x8e, 0x13, 0x48, 0x36, 0xb3, 0xf9, 0xc1, 0x67, 0xf2, 0xc1, 0x86, 0x8f, 0x2f, 0x13, 0xe6,
	0xfb, 0x5a, 0x82, 0xda, 0xec, 0x2a, 0x50, 0xa9, 0x2a, 0x87, 0x4a, 0x31, 0x49, 0x5b, 0x68, 0x41,
	0xa9, 0x9b, 0x82, 0x54, 0xa9, 0x72, 0x67, 0xed, 0x61, 0x33, 0x64, 0xed, 0x71, 0x3d, 0xb3, 0x4b,
	0x56, 0xea, 0xa1, 0x52, 0x2f, 0x1c, 0x39, 0x22, 0xf5, 0xc2, 0x1f, 0xd1, 0xbf, 0xa1, 0xa2, 0x9c,
	0x38, 0x56, 0x3d, 0xb8, 0x15, 0x5c, 0xaa, 0x3d, 0xba, 0x87, 0x5e, 0x2b, 0xcf, 0x8f, 0xb5, 0xd7,
	0x21, 0x42, 0x54, 0xe2, 0x54, 0x4e, 0xf1, 0x3c, 0xcf, 0x3b, 0xef, 0xfb, 0x8e, 0xdf, 0xe7, 0x7d,
	0xbd, 0x13, 0x80, 0xb8, 0x48, 0xb0, 0x60, 0xbc, 0x95, 0x90, 0x0e, 0xe5, 0x82, 0x24, 0xad, 0xfe,
	0xc6, 0xe8, 0xb9, 0x19, 0x27, 0x4c, 0x30, 0xfb, 0xa4, 0xb6, 0x69, 0x8e, 0xf0, 0xfe, 0xc6, 0x99,
	0xa5, 0x0e, 0xeb, 0x30, 0xc9, 0xb7, 0xf2, 0x27, 0x65, 0x7a, 0x66, 0xb9, 0xc3, 0x58, 0xa7, 0x4b,
	0x5a, 0x72, 0xd5, 0xee, 0xdd, 0x6e, 0xe1, 0x68, 0xa0, 0x29, 0x58, 0xa5, 0x04, 0x0d, 0x09, 0x17,
	0x38, 0x8c, 0xb5, 0xc1, 0x4a, 0xd5, 0x20, 0xe8, 0x25, 0x58, 0x50, 0x16, 0x19, 0xdf, 0x3e, 0xe3,
	0x21, 0xe3, 0x9e, 0x0a, 0xaa, 0x16, 0x66, 0xab, 0x5a, 0xb5, 0xda, 0x98, 0x93, 0x56, 0x7f, 0xa3,
	0x4d, 0x04, 0xde, 0x68, 0xf9, 0x8c, 0x9a, 0xad, 0xff, 0xd7, 0x3c, 0x17, 0x78, 0x9f, 0x46, 0x9d,
	0x91, 0x89, 0x5e, 0x2b, 0x2b, 0xf4, 0xc7, 0x34, 0x98, 0xde, 0xc1, 0x09, 0x0e, 0xb9, 0xed, 0x00,
	0xd0, 0x66, 0x51, 0xe0, 0x05, 0x24, 0x62, 0x61, 0xc3, 0x5a, 0xb5, 0xd6, 0x66, 0x9d, 0xff, 0x0d,
	0x53, 0x58, 0x42, 0xb3, 0x14, 0xfe, 0x6b, 0x80, 0xc3, 0xee, 0x65, 0x54, 0x60, 0xc8, 0x9d, 0xcd,
	0x17, 0x5b, 0xf9, 0xb3, 0xfd, 0xd0, 0x02, 0xcb, 0xbd, 0x28, 0x5f, 0xd3, 0xa8, 0xe3, 0x89, 0xbd,
	0x84, 0x60, 0xbe, 0xc7, 0xba, 0x81, 0x97, 0x1f, 0xbc, 0x31, 0xb9, 0x6a, 0xad, 0xd5, 0x2f, 0x2e,
	0x37, 0xd5, 0xa1, 0x9b, 0xe6, 0xd0, 0xcd, 0x2d, 0x7d, 0x68, 0xe7, 0xea, 0xa3, 0x14, 0x4e, 0x0c,
	0x53, 0x78, 0xb4, 0x8f, 0x2c, 0x85, 0xab, 0x2a, 0x83, 0x23, 0x4d, 0xd0, 0x83, 0x5f, 0xa1, 0xe5,
	0x9e, 0x1e, 0xf1, 0xbb, 0x23, 0x7a, 0x97, 0x86, 0xa4, 0x92, 0xa2, 0xcf, 0xc2, 0xb8, 0x4b, 0xf2,
	0xe0, 0x2a, 0xc5, 0xa9, 0xbf, 0x91, 0x62, 0xc5, 0xc7, 0xf3, 0x52, 0xac, 0x98, 0x54, 0x53, 0xbc,
	0x32, 0xa2, 0x65, 0x8a, 0x3b, 0xa0, 0x1e, 0xe2, 0x03, 0x8f, 0x44, 0x22, 0xa1, 0x84, 0x37, 0x8e,
	0xad, 0x5a, 0x6b, 0xf3, 0x4e, 0x6b, 0x98, 0xc2, 0x32, 0x9c, 0xa5, 0xf0, 0xac, 0x0a, 0x53, 0x02,
	0xd1, 0xdb, 0x2c, 0xa4, 0x82, 0x84, 0xb1, 0x18, 0xb8, 0x20, 0xc4, 0x07, 0xdb, 0x0a, 0xb6, 0xbf,
	0x01, 0xcb, 0x09, 0xe1, 0xac, 0x97, 0xf8, 0xc4, 0x8b, 0x58, 0x40, 0xbc, 0x84, 0x74, 0x3c, 0x12,
	0xe1, 0x76, 0x97, 0x04, 0x8d, 0xe3, 0xab, 0xd6, 0x5a, 0xcd, 0xd9, 0xcc, 0x0f, 0x75, 0xa4, 0x51,
	0x71, 0xa8, 0x23, 0x4d, 0x90, 0x7b, 0xca, 0x70, 0x37, 0x58, 0x40, 0x5c, 0xd2, 0xd9, 0x56, 0x84,
	0xfd, 0xbd, 0x55, 0x0d, 0x1f, 0xd2, 0xc8, 0x0b, 0x48, 0xcc, 0x38, 0x15, 0x8d, 0x69, 0xfd, 0xca,
	0xb5, 0xba, 0x73, 0x3d, 0x37, 0xb5, 0x58, 0x9b, 0x57, 0x18, 0x8d, 0x9c, 0x6d, 0xf3, 0xca, 0x8f,
	0xf4, 0x71, 0x54, 0x76, 0x25, 0x93, 0x4a, 0x76, 0xd7, 0x69, 0xb4, 0xa5, 0x08, 0xfb, 0x6b, 0x30,
	0xdf, 0x67, 0x22, 0xaf, 0x52, 0x4c, 0x12, 0xca, 0x82, 0xc6, 0xcc, 0x8b, 0x34, 0xb0, 0xa1, 0x13,
	0x1a, 0xdf, 0x97, 0xa5, 0x70, 0x49, 0x25, 0x31, 0x06, 0xab, 0x5a, 0xcf, 0x29, 0x6c, 0x47, 0x41,
	0x3f, 0xce, 0x80, 0x39, 0xb7, 0x94, 0x8d, 0x7d, 0x13, 0x2c, 0x46, 0x44, 0xdc, 0x65, 0xc9, 0xbe,
	0x87, 0x83, 0x20, 0x21, 0x9c, 0xeb, 0x06, 0x5c, 0x1f, 0xa6, 0xb0, 0x4a, 0x65, 0x29, 0x3c, 0xa5,
	0x02, 0x55, 0x08, 0xe4, 0x2e, 0x68, 0x64, 0x53, 0x01, 0x36, 0x06, 0xd3, 0x71, 0xaf, 0xbd, 0x4f,
	0x06, 0xba, 0xf7, 0x96, 0x0e, 0x1d, 0x6a, 0x33, 0x1a, 0x38, 0x97, 0x86, 0x29, 0xd4, 0x76, 0x59,
	0x0a, 0xe7, 0x95, 0x6f, 0xb5, 0x46, 0x8f, 0x7f, 0x58, 0x5f, 0xd2, 0x95, 0xf1, 0x93, 0x41, 0x2c,
	0x58, 0x73, 0xa7, 0xd7, 0xfe, 0x98, 0x0c, 0x5c, 0xbd, 0xc1, 0x7e, 0x17, 0xcc, 0xf0, 0x1e, 0x8f,
	0x49, 0x14, 0xc8, 0xe6, 0xa9, 0x39, 0xff, 0x1d, 0xa6, 0xd0, 0x40, 0x59, 0x0a, 0x17, 0x94, 0x3b,
	0x0d, 0x20, 0xd7, 0x50, 0xf6, 0x2d, 0x30, 0xcd, 0x05, 0x16, 0x3d, 0x25, 0xf0, 0x85, 0x8b, 0xc8,
	0x28, 0xc0, 0x4c, 0x28, 0x23, 0x02, 0x87, 0x45, 0xc1, 0x67, 0xd2, 0xd2, 0xf9, 0x4f, 0x9e, 0xa9,
	0xda, 0x55, 0x64, 0xaa, 0xd6, 0xc8, 0xd5, 0x44, 0x7e, 0x68, 0xc1, 0xf6, 0x49, 0xc4, 0xa5, 0xb2,
	0x67, 0x55, 0xcb, 0xfe, 0x92, 0xc2, 0x37, 0x3b, 0x54, 0xec, 0xf5, 0xda, 0x4d, 0x9f, 0x85, 0x7a,
	0x94, 0xea, 0x3f, 0xeb, 0x3c, 0xd8, 0x6f, 0x89, 0x41, 0x4c, 0x78, 0xf3, 0x6a, 0x24, 0xf2, 0x10,
	0x6a, 0x7f, 0x11, 0x42, 0xad, 0x91, 0xab, 0x09, 0xfb, 0x06, 0x98, 0x67, 0x77, 0x23, 0x92, 0x8c,
	0xaa, 0x35, 0x2d, 0x23, 0x5d, 0xc8, 0x45, 0x31, 0x46, 0x14, 0xa2, 0x18, 0x83, 0x91, 0x3b, 0x27,
	0xd7, 0xa6, 0x4e, 0x21, 0xa8, 0x07, 0x84, 0xfb, 0x09, 0x8d, 0x73, 0x81, 0x69, 0x05, 0xae, 0x36,
	0x9f, 0xf3, 0x11, 0x6a, 0x6e, 0x15, 0x76, 0xce, 0x05, 0x2d, 0xc4, 0xf2, 0xe6, 0x2c, 0x85, 0xb6,
	0x8a, 0x58, 0x02, 0x91, 0x5b, 0x36, 0xb1, 0x13, 0x30, 0xef, 0x27, 0x04, 0x17, 0x63, 0xaf, 0x26,
	0x03, 0x9e, 0x39, 0xa4, 0x8e, 0x5d, 0xf3, 0xbd, 0x2a, 0x34, 0x3f, 0xb6, 0xb1, 0x38, 0xde, 0x18,
	0x8c, 0xee, 0x4b, 0xcd, 0x1b, 0x4c, 0x0e, 0xb5, 0xf7, 0xc1, 0xac, 0xec, 0xc9, 0xfc, 0x3d, 0x37,
	0x66, 0xe5, 0x48, 0x3b, 0x37, 0x4c, 0x61, 0x01, 0x66, 0x29, 0x3c, 0xa1, 0x65, 0x6d, 0x20, 0xe4,
	0xd6, 0xf2, 0xe7, 0xdd, 0x41, 0x4c, 0xec, 0x7b, 0x16, 0x38, 0x41, 0x6e, 0xdf, 0x26, 0xbe, 0xa0,
	0x7d, 0xe2, 0xe9, 0x02, 0x03, 0xf9, 0xda, 0xbf, 0x7c, 0xe9, 0x02, 0x1f, 0xf2, 0x94, 0xa5, 0xf0,
	0xb4, 0x0a, 0x5e, 0x65, 0x90, 0xbb, 0x38, 0x82, 0x76, 0x25, 0x72, 0xb9, 0xf6, 0xe0, 0x21, 0xb4,
	0x7e, 0x7f, 0x08, 0x2d, 0xf4, 0xe7, 0x71, 0x50, 0xbb, 0x4e, 0x04, 0x7e, 0xdd, 0xc4, 0xaf, 0x9b,
	0xf8, 0x1f, 0xd0, 0xc4, 0x25, 0xe5, 0xff, 0x34, 0x05, 0xce, 0x1a, 0xe5, 0xbb, 0xf2, 0x64, 0xea,
	0xe3, 0x78, 0x93, 0x09, 0xb2, 0xc3, 0x58, 0xf7, 0x95, 0x75, 0xc3, 0x35, 0x30, 0x87, 0xe3, 0x38,
	0x61, 0x7d, 0xe2, 0x75, 0x29, 0x17, 0x8d, 0xc9, 0xd5, 0xa9, 0xb5, 0x59, 0xe7, 0xfc, 0x30, 0x85,
	0x63, 0x78, 0x96, 0xc2, 0x93, 0xca, 0x63, 0x19, 0x45, 0x6e, 0x5d, 0x2f, 0x3f, 0xa1, 0x5c, 0xd8,
	0x1f, 0x80, 0x7a, 0x42, 0xee, 0x10, 0x5f, 0x28, 0x57, 0x53, 0xd2, 0xd5, 0x1b, 0x79, 0x2d, 0x4a,
	0x70, 0x51, 0x8b, 0x12, 0x88, 0x5c, 0xa0, 0x56, 0xd2, 0xcf, 0x1d, 0x50, 0x27, 0x07, 0x31, 0x4d,
	0x88, 0x2a, 0xc4, 0xb1, 0x17, 0x16, 0x62, 0xdd, 0xd4, 0xbc, 0xb4, 0xad, 0x88, 0x53, 0x02, 0x55,
	0x11, 0x80, 0x42, 0xe4, 0x1c, 0xfd, 0x14, 0x2c, 0x50, 0xee, 0xf5, 0x99, 0x20, 0x5e, 0x8c, 0x39,
	0x1f, 0xfd, 0x7e, 0x7b, 0x6b, 0x98, 0xc2, 0x0a, 0x93, 0xa5, 0xf0, 0xdf, 0xca, 0xe3, 0x38, 0x8e,
	0xdc, 0x39, 0xca, 0x65, 0xa1, 0xd4, 0xf2, 0xbb, 0x29, 0x50, 0x2f, 0x29, 0x32, 0x9f, 0x06, 0x21,
	0x8b, 0xe8, 0x3e, 0x49, 0x74, 0xc9, 0xe4, 0x34, 0xd0, 0x50, 0x31, 0x0d, 0x34, 0x80, 0x5c, 0x43,
	0xd9, 0xdb, 0xa0, 0x46, 0x03, 0x12, 0x09, 0x2a, 0xd4, 0xac, 0x52, 0xcd, 0x34, 0xc2, 0xb2, 0x14,
	0x2e, 0xeb, 0x7c, 0x34, 0x52, 0xfe, 0xbd, 0x3a, 0x32, 0xb3, 0x37, 0xc1, 0xcc, 0x5d, 0xd2, 0xe6,
	0x54, 0xa8, 0xdf, 0xe3, 0xaa, 0xba, 0x06, 0xca, 0x52, 0xd8, 0x50, 0x4e, 0x34, 0x50, 0xf6, 0x61,
	0x8c, 0xec, 0x00, 0x9c, 0xe0, 0xc4, 0xef, 0x25, 0x54, 0x0c, 0x3c, 0x9f, 0x45, 0x02, 0xfb, 0x42,
	0x96, 0x65, 0xd6, 0x79, 0x2f, 0x1f, 0xff, 0x55, 0x2e, 0x4b, 0xe1, 0x39, 0x3d, 0x87, 0x2a, 0x4c,
	0xd9, 0xfb, 0xa2, 0x21, 0xaf, 0x28, 0x2e, 0x4f, 0x34, 0x20, 0x02, 0xd3, 0xae, 0x99, 0x52, 0x32,
	0x51, 0x0d, 0x15, 0x89, 0x6a, 0x60, 0x2c, 0x51, 0x8d, 0x95, 0x3a, 0xea, 0xde, 0x24, 0x98, 0xff,
	0xdc, 0xdc, 0x08, 0xe4, 0x07, 0xe5, 0x1a, 0x98, 0x2b, 0xb7, 0x83, 0x2e, 0x86, 0x94, 0x7a, 0x19,
	0x2f, 0xa4, 0x5e, 0x46, 0x91, 0x5b, 0x2f, 0x75, 0x8e, 0x7d, 0x15, 0xcc, 0x51, 0xee, 0x85, 0x44,
	0x60, 0xf9, 0xd3, 0x58, 0x96, 0xa7, 0xa6, 0x7c, 0x95, 0xf1, 0xc2, 0x57, 0x19, 0x45, 0x2e, 0xa0,
	0x7c, 0xf4, 0x9d, 0xfb, 0x0a, 0xcc, 0x98, 0xab, 0x49, 0xde, 0x31, 0xf5, 0x8b, 0xe7, 0x9f, 0x3b,
	0xe3, 0xc6, 0xce, 0x92, 0x5f, 0x44, 0x06, 0x4a, 0x47, 0xc5, 0xfd, 0x45, 0xeb, 0xc8, 0xdc, 0x5d,
	0x5c, 0x43, 0xa1, 0xc7, 0x53, 0xc0, 0x3e, 0xbc, 0x3d, 0x1f, 0x29, 0xa3, 0x09, 0xb5, 0x47, 0x68,
	0x67, 0x4f, 0xc8, 0x57, 0x32, 0xa5, 0x46, 0x4a, 0x85, 0x2a, 0x46, 0x4a, 0x85, 0x40, 0xee, 0x82,
	0x41, 0x3e, 0x92, 0x80, 0xdd, 0x07, 0x8b, 0xd5, 0x7b, 0xe0, 0xe4, 0xab, 0x98, 0xa5, 0x0b, 0xfe,
	0xf8, 0x3d, 0xef, 0x5b, 0x0b, 0x2c, 0xd2, 0x88, 0x0a, 0x8a, 0xbb, 0x5e, 0x1b, 0x77, 0x71, 0xe4,
	0x1b, 0xc1, 0xdf, 0x7a, 0xa9, 0x2f, 0x5d, 0xd5, 0x49, 0x71, 0xf4, 0x0a, 0x81, 0xdc, 0x05, 0x8d,
	0x38, 0x0a, 0xb0, 0x31, 0x98, 0x31, 0x91, 0x55, 0x7b, 0x7c, 0xf8, 0x52, 0x91, 0x67, 0x8a, 0x88,
	0xba, 0x98, 0xa3, 0x48, 0x86, 0x72, 0x6e, 0x3c, 0x7a, 0xba, 0x62, 0x3d, 0x79, 0xba, 0x62, 0xfd,
	0xf6, 0x74, 0xc5, 0xba, 0xff, 0x6c, 0x65, 0xe2, 0xc9, 0xb3, 0x95, 0x89, 0x9f, 0x9f, 0xad, 0x4c,
	0x7c, 0xf1, 0x4e, 0x29, 0x8e, 0x56, 0x50, 0x44, 0x84, 0x79, 0x5c, 0xf7, 0xf7, 0x30, 0x8d, 0x5a,
	0x07, 0xc5, 0xbf, 0x69, 0x64, 0xe4, 0xf6, 0xb4, 0x2c, 0xc6, 0xa5, 0xbf, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0x59, 0x8d, 0xfe, 0xc7, 0x11, 0x00, 0x00,
}

func (this *ResourceNode) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResourceNode)
	if !ok {
		that2, ok := that.(ResourceNode)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NetworkAddress != that1.NetworkAddress {
		return false
	}
	if !this.Pubkey.Equal(that1.Pubkey) {
		return false
	}
	if this.Suspend != that1.Suspend {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.Tokens.Equal(that1.Tokens) {
		return false
	}
	if this.OwnerAddress != that1.OwnerAddress {
		return false
	}
	if !this.Description.Equal(&that1.Description) {
		return false
	}
	if !this.CreationTime.Equal(that1.CreationTime) {
		return false
	}
	if this.NodeType != that1.NodeType {
		return false
	}
	if !this.EffectiveTokens.Equal(that1.EffectiveTokens) {
		return false
	}
	return true
}
func (this *MetaNode) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MetaNode)
	if !ok {
		that2, ok := that.(MetaNode)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NetworkAddress != that1.NetworkAddress {
		return false
	}
	if !this.Pubkey.Equal(that1.Pubkey) {
		return false
	}
	if this.Suspend != that1.Suspend {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.Tokens.Equal(that1.Tokens) {
		return false
	}
	if this.OwnerAddress != that1.OwnerAddress {
		return false
	}
	if !this.Description.Equal(&that1.Description) {
		return false
	}
	if !this.CreationTime.Equal(that1.CreationTime) {
		return false
	}
	return true
}
func (this *Description) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Description)
	if !ok {
		that2, ok := that.(Description)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Moniker != that1.Moniker {
		return false
	}
	if this.Identity != that1.Identity {
		return false
	}
	if this.Website != that1.Website {
		return false
	}
	if this.SecurityContact != that1.SecurityContact {
		return false
	}
	if this.Details != that1.Details {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.VotingPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.VotingPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintRegister(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.ResourceNodeMinDeposit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRegister(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.ResourceNodeRegEnabled {
		i--
		if m.ResourceNodeRegEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.MaxEntries != 0 {
		i = encodeVarintRegister(dAtA, i, uint64(m.MaxEntries))
		i--
		dAtA[i] = 0x20
	}
	n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.UnbondingCompletionTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.UnbondingCompletionTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintRegister(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x1a
	n4, err4 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.UnbondingThreasholdTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.UnbondingThreasholdTime):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintRegister(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x12
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResourceNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.EffectiveTokens.Size()
		i -= size
		if _, err := m.EffectiveTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegister(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.NodeType != 0 {
		i = encodeVarintRegister(dAtA, i, uint64(m.NodeType))
		i--
		dAtA[i] = 0x48
	}
	n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreationTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreationTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintRegister(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x42
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRegister(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.Tokens.Size()
		i -= size
		if _, err := m.Tokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegister(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Status != 0 {
		i = encodeVarintRegister(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.Suspend {
		i--
		if m.Suspend {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Pubkey != nil {
		{
			size, err := m.Pubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRegister(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NetworkAddress) > 0 {
		i -= len(m.NetworkAddress)
		copy(dAtA[i:], m.NetworkAddress)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.NetworkAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MetaNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetaNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n8, err8 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreationTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreationTime):])
	if err8 != nil {
		return 0, err8
	}
	i -= n8
	i = encodeVarintRegister(dAtA, i, uint64(n8))
	i--
	dAtA[i] = 0x42
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRegister(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.Tokens.Size()
		i -= size
		if _, err := m.Tokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegister(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Status != 0 {
		i = encodeVarintRegister(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.Suspend {
		i--
		if m.Suspend {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Pubkey != nil {
		{
			size, err := m.Pubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRegister(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NetworkAddress) > 0 {
		i -= len(m.NetworkAddress)
		copy(dAtA[i:], m.NetworkAddress)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.NetworkAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MetaNodeRegistrationVotePool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaNodeRegistrationVotePool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetaNodeRegistrationVotePool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsVotePassed {
		i--
		if m.IsVotePassed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	n11, err11 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.ExpireTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.ExpireTime):])
	if err11 != nil {
		return 0, err11
	}
	i -= n11
	i = encodeVarintRegister(dAtA, i, uint64(n11))
	i--
	dAtA[i] = 0x22
	if len(m.RejectList) > 0 {
		for iNdEx := len(m.RejectList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RejectList[iNdEx])
			copy(dAtA[i:], m.RejectList[iNdEx])
			i = encodeVarintRegister(dAtA, i, uint64(len(m.RejectList[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ApproveList) > 0 {
		for iNdEx := len(m.ApproveList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ApproveList[iNdEx])
			copy(dAtA[i:], m.ApproveList[iNdEx])
			i = encodeVarintRegister(dAtA, i, uint64(len(m.ApproveList[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.NetworkAddress) > 0 {
		i -= len(m.NetworkAddress)
		copy(dAtA[i:], m.NetworkAddress)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.NetworkAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Description) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Description) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Description) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Details) > 0 {
		i -= len(m.Details)
		copy(dAtA[i:], m.Details)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.Details)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SecurityContact) > 0 {
		i -= len(m.SecurityContact)
		copy(dAtA[i:], m.SecurityContact)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.SecurityContact)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Website) > 0 {
		i -= len(m.Website)
		copy(dAtA[i:], m.Website)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.Website)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Identity) > 0 {
		i -= len(m.Identity)
		copy(dAtA[i:], m.Identity)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.Identity)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UnbondingNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRegister(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.IsMetaNode {
		i--
		if m.IsMetaNode {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.NetworkAddr) > 0 {
		i -= len(m.NetworkAddr)
		copy(dAtA[i:], m.NetworkAddr)
		i = encodeVarintRegister(dAtA, i, uint64(len(m.NetworkAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UnbondingNodeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingNodeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingNodeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Balance != nil {
		{
			size := m.Balance.Size()
			i -= size
			if _, err := m.Balance.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintRegister(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.InitialBalance != nil {
		{
			size := m.InitialBalance.Size()
			i -= size
			if _, err := m.InitialBalance.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintRegister(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	n12, err12 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CompletionTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CompletionTime):])
	if err12 != nil {
		return 0, err12
	}
	i -= n12
	i = encodeVarintRegister(dAtA, i, uint64(n12))
	i--
	dAtA[i] = 0x12
	if m.CreationHeight != 0 {
		i = encodeVarintRegister(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRegister(dAtA []byte, offset int, v uint64) int {
	offset -= sovRegister(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.UnbondingThreasholdTime)
	n += 1 + l + sovRegister(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.UnbondingCompletionTime)
	n += 1 + l + sovRegister(uint64(l))
	if m.MaxEntries != 0 {
		n += 1 + sovRegister(uint64(m.MaxEntries))
	}
	if m.ResourceNodeRegEnabled {
		n += 2
	}
	l = m.ResourceNodeMinDeposit.Size()
	n += 1 + l + sovRegister(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.VotingPeriod)
	n += 1 + l + sovRegister(uint64(l))
	return n
}

func (m *ResourceNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NetworkAddress)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	if m.Pubkey != nil {
		l = m.Pubkey.Size()
		n += 1 + l + sovRegister(uint64(l))
	}
	if m.Suspend {
		n += 2
	}
	if m.Status != 0 {
		n += 1 + sovRegister(uint64(m.Status))
	}
	l = m.Tokens.Size()
	n += 1 + l + sovRegister(uint64(l))
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = m.Description.Size()
	n += 1 + l + sovRegister(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreationTime)
	n += 1 + l + sovRegister(uint64(l))
	if m.NodeType != 0 {
		n += 1 + sovRegister(uint64(m.NodeType))
	}
	l = m.EffectiveTokens.Size()
	n += 1 + l + sovRegister(uint64(l))
	return n
}

func (m *MetaNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NetworkAddress)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	if m.Pubkey != nil {
		l = m.Pubkey.Size()
		n += 1 + l + sovRegister(uint64(l))
	}
	if m.Suspend {
		n += 2
	}
	if m.Status != 0 {
		n += 1 + sovRegister(uint64(m.Status))
	}
	l = m.Tokens.Size()
	n += 1 + l + sovRegister(uint64(l))
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = m.Description.Size()
	n += 1 + l + sovRegister(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreationTime)
	n += 1 + l + sovRegister(uint64(l))
	return n
}

func (m *MetaNodeRegistrationVotePool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NetworkAddress)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	if len(m.ApproveList) > 0 {
		for _, s := range m.ApproveList {
			l = len(s)
			n += 1 + l + sovRegister(uint64(l))
		}
	}
	if len(m.RejectList) > 0 {
		for _, s := range m.RejectList {
			l = len(s)
			n += 1 + l + sovRegister(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.ExpireTime)
	n += 1 + l + sovRegister(uint64(l))
	if m.IsVotePassed {
		n += 2
	}
	return n
}

func (m *Description) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = len(m.Identity)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = len(m.Website)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = len(m.SecurityContact)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	l = len(m.Details)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	return n
}

func (m *UnbondingNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NetworkAddr)
	if l > 0 {
		n += 1 + l + sovRegister(uint64(l))
	}
	if m.IsMetaNode {
		n += 2
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovRegister(uint64(l))
		}
	}
	return n
}

func (m *UnbondingNodeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreationHeight != 0 {
		n += 1 + sovRegister(uint64(m.CreationHeight))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CompletionTime)
	n += 1 + l + sovRegister(uint64(l))
	if m.InitialBalance != nil {
		l = m.InitialBalance.Size()
		n += 1 + l + sovRegister(uint64(l))
	}
	if m.Balance != nil {
		l = m.Balance.Size()
		n += 1 + l + sovRegister(uint64(l))
	}
	return n
}

func sovRegister(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRegister(x uint64) (n int) {
	return sovRegister(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingThreasholdTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.UnbondingThreasholdTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingCompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.UnbondingCompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEntries", wireType)
			}
			m.MaxEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceNodeRegEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ResourceNodeRegEnabled = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceNodeMinDeposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ResourceNodeMinDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.VotingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResourceNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResourceNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResourceNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pubkey == nil {
				m.Pubkey = &types1.Any{}
			}
			if err := m.Pubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Suspend", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Suspend = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types2.BondStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeType", wireType)
			}
			m.NodeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EffectiveTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetaNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pubkey == nil {
				m.Pubkey = &types1.Any{}
			}
			if err := m.Pubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Suspend", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Suspend = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types2.BondStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetaNodeRegistrationVotePool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaNodeRegistrationVotePool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaNodeRegistrationVotePool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApproveList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApproveList = append(m.ApproveList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RejectList = append(m.RejectList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.ExpireTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVotePassed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVotePassed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Description) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Description: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Description: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Identity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Website", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Website = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityContact", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecurityContact = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMetaNode", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMetaNode = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &UnbondingNodeEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingNodeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingNodeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingNodeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Int
			m.InitialBalance = &v
			if err := m.InitialBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegister
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegister
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Int
			m.Balance = &v
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegister(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegister
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRegister(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRegister
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegister
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRegister
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRegister
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRegister
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRegister        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRegister          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRegister = fmt.Errorf("proto: unexpected end of group")
)
